n1 = int(input("Enter n1: "))
n2 = int(input("Enter n2: "))
print("Bitwise Operators")
print(f"Bitwise And(&): {n1&n2}")
print(f"Bitwise Or(|): {n1|n2}")
print(f"Bitwise Not(^) of {n1}: {~n1}")
print(f"Bitwise Not(^): {~n2}")
print(f"Bitwise right shift >>: {n1>>n2}")
print(f"Bitwise left shift operator: {n1 << n2}")
print(f"Bitwies XOR: {n1^n2}")